# setup-tunnels.ps1
# Automates devtunnel hosting and injection into Flutter api_config.dart

$ProjectRoot = Get-Location
$ApiConfigPath = Join-Path $ProjectRoot "frontend\mobile\lib\config\api_config.dart"

Write-Host "NERDCO DevTunnel Automation" -ForegroundColor Cyan
Write-Host "----------------------------"

# 1. Check for devtunnel
if (!(Get-Command devtunnel -ErrorAction SilentlyContinue)) {
    Write-Error "devtunnel not found. Please install it (e.g., 'choco install devtunnel') and try again."
    exit 1
}

# 2. Check if logged in
$user = devtunnel user show | Out-String
if ($user -match "not logged in") {
    Write-Host "Logging into devtunnel..."
    devtunnel user login
}

# 3. Start tunnel in a new window
Write-Host "Starting devtunnel for ports 3001, 3002, 3003, 3004..." -ForegroundColor Yellow
Start-Process powershell -ArgumentList "-NoExit", "-Command", "devtunnel host -p 3001 3002 3003 3004 --allow-anonymous"

Write-Host "Waiting 5 seconds for tunnel to initialize..."
Start-Sleep -Seconds 5

# 4. Extract URLs
Write-Host "Extracting tunnel URLs..." -ForegroundColor Yellow
$tunnels = devtunnel list --json | ConvertFrom-Json
if ($null -eq $tunnels -or $tunnels.Count -eq 0) {
    Write-Host "No active tunnels found. Please ensure the host command is running in the other window." -ForegroundColor Red
    exit 1
}

# Find the hosting tunnel (usually only one active host)
$tunnel = $tunnels | Where-Object { $_.endpoints.Count -gt 0 } | Select-Object -First 1

if ($null -eq $tunnel) {
    Write-Host "Could not find an active tunnel with endpoints. Is it still starting?" -ForegroundColor Red
    exit 1
}

$TunnelId = $tunnel.tunnelId
$Cluster = $tunnel.clusterId

# Construct URLs (devtunnel URLs follow a pattern: {tunnelId}-{port}.{clusterId}.devtunnels.ms)
$AuthUrl      = "https://$TunnelId-3001.$Cluster.devtunnels.ms"
$IncidentUrl  = "https://$TunnelId-3002.$Cluster.devtunnels.ms"
$TrackingUrl  = "https://$TunnelId-3003.$Cluster.devtunnels.ms"
$AnalyticsUrl = "https://$TunnelId-3004.$Cluster.devtunnels.ms"
$WsUrl        = "wss://$TunnelId-3003.$Cluster.devtunnels.ms/ws/vehicles"

Write-Host "Detected Tunnel ID: $TunnelId"
Write-Host "Auth Base:      $AuthUrl"
Write-Host "Incident Base:  $IncidentUrl"
Write-Host "Tracking Base:  $TrackingUrl"
Write-Host "Analytics Base: $AnalyticsUrl"

# 5. Inject into api_config.dart
Write-Host "Updating api_config.dart..." -ForegroundColor Green

$ConfigContent = @"
/// Base URLs for each backend service.
/// AUTO-GENERATED BY setup-tunnels.ps1
class ApiConfig {
  static const String authUrl      = '$AuthUrl';
  static const String incidentUrl  = '$IncidentUrl';
  static const String trackingUrl  = '$TrackingUrl';
  static const String analyticsUrl = '$AnalyticsUrl';

  /// WebSocket endpoint for live vehicle positions
  static const String vehicleWsUrl = '$WsUrl';
}
"@

$ConfigContent | Out-File -FilePath $ApiConfigPath -Encoding utf8

Write-Host "Success! Your mobile app is now pointing to the devtunnel backend." -ForegroundColor Green
Write-Host "You can now run 'flutter run' on your device."
