# setup-local-ip.ps1
# Automates finding the PC's Wi-Fi LAN IP and injecting it into Flutter api_config.dart

$ProjectRoot = Get-Location
$ApiConfigPath = Join-Path $ProjectRoot "frontend\mobile\lib\config\api_config.dart"

Write-Host "NERDCO Local LAN IP Setup" -ForegroundColor Cyan
Write-Host "---------------------------"

# 1. Find the internal IP Address
Write-Host "Detecting LAN IP..." -ForegroundColor Yellow
$IP = (Get-NetIPAddress -AddressFamily IPv4 `
    | Where-Object { $_.IPAddress -match "^192\.168\." -or $_.IPAddress -match "^10\." -or $_.IPAddress -match "^172\.(1[6-9]|2[0-9]|3[0-1])\." } `
    | Select-Object -First 1).IPAddress

if (-not $IP) {
    Write-Host "Could not automatically detect your local IPv4 address." -ForegroundColor Red
    exit 1
}

Write-Host "Found Local IP: $IP" -ForegroundColor Green

# 2. Inject into api_config.dart
Write-Host "Updating api_config.dart..." -ForegroundColor Yellow

# Use a template string that avoids PowerShell variable expansion during string creation if needed, 
# or use $($var) to ensure clean expansion before writing.
$ConfigContent = @"
/// Base URLs for each backend service.
/// AUTO-GENERATED BY setup-local-ip.ps1
/// This points to your current Wi-Fi LAN IP.
class ApiConfig {
  static const String authUrl      = 'http://$($IP):3001';
  static const String incidentUrl  = 'http://$($IP):3002';
  static const String trackingUrl  = 'http://$($IP):3003';
  static const String analyticsUrl = 'http://$($IP):3004';

  /// WebSocket endpoint for live vehicle positions
  static const String vehicleWsUrl = 'ws://$($IP):3003/ws/vehicles';
}
"@

$ConfigContent | Out-File -FilePath $ApiConfigPath -Encoding utf8

Write-Host "Success! The mobile app is fully configured to connect to your local backend ($IP)." -ForegroundColor Green
Write-Host "CRITICAL: Ensure your mobile device is connected to the exact same Wi-Fi network!" -ForegroundColor Red
